# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Custom action terms for G1 locomotion tasks."""

from __future__ import annotations

import torch

from isaaclab.envs.mdp.actions.joint_actions import JointPositionAction


class StandingArmBlendJointPositionAction(JointPositionAction):
    """Joint position action that overrides arm joints with trajectory disturbance targets.

    This keeps the action dimension unchanged while enforcing arm motions generated by
    the standing arm-disturbance curriculum.
    """

    def __init__(self, cfg, env):
        super().__init__(cfg, env)
        name_to_col = {name: idx for idx, name in enumerate(self._joint_names)}
        arm_cols = []
        for name in self._joint_names:
            is_arm_joint = ("shoulder" in name) or ("elbow" in name)
            if is_arm_joint:
                arm_cols.append(name_to_col[name])
        self._arm_action_cols = torch.tensor(arm_cols, dtype=torch.long, device=self.device) if arm_cols else None

    def apply_actions(self):
        targets = self.processed_actions.clone()

        arm_motion_targets = getattr(self._env, "_standing_arm_motion_targets", None)
        arm_motion_joint_ids = getattr(self._env, "_standing_arm_motion_joint_ids", None)

        if (
            self._arm_action_cols is not None
            and arm_motion_targets is not None
            and arm_motion_joint_ids is not None
            and len(self._arm_action_cols) > 0
        ):
            action_joint_ids = self._joint_ids
            if isinstance(action_joint_ids, slice):
                action_joint_ids = torch.arange(self._asset.num_joints, device=self.device)
            else:
                action_joint_ids = torch.tensor(action_joint_ids, dtype=torch.long, device=self.device)

            # Map each disturbed arm joint id onto the corresponding action-space column.
            id_to_action_col = {int(jid): idx for idx, jid in enumerate(action_joint_ids.tolist())}
            mapped_cols = []
            mapped_src = []
            for src_idx, joint_id in enumerate(arm_motion_joint_ids.tolist()):
                col = id_to_action_col.get(int(joint_id))
                if col is not None:
                    mapped_cols.append(col)
                    mapped_src.append(src_idx)
            if len(mapped_cols) > 0:
                col_t = torch.tensor(mapped_cols, dtype=torch.long, device=self.device)
                src_t = torch.tensor(mapped_src, dtype=torch.long, device=self.device)
                targets[:, col_t] = arm_motion_targets[:, src_t]

        self._asset.set_joint_position_target(targets, joint_ids=self._joint_ids)
